# Generated by Django 4.2.5 on 2023-12-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0065_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='archive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
