# Generated by Django 4.2.5 on 2023-12-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0066_enquiry_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='assign_to_documentation_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentation_emp', to='crm_app.employee'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='assign_to_sales_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_emp', to='crm_app.employee'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='assign_to_visa_team_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visa_team_emp', to='crm_app.employee'),
        ),
    ]
