# Generated by Django 4.2.5 on 2023-12-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0067_enquiry_assign_to_documentation_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Presales/Assesment', 'Presales/Assesment'), ('Sales', 'Sales'), ('Documentation', 'Documentation'), ('VisaTeam', 'VisaTeam'), ('HR', 'HR')], max_length=100),
        ),
    ]
