# Generated by Django 4.2.5 on 2023-12-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0068_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
